name: fluent_assertions
description: Fluent Assertions library written in Dart.
version: 0.2.0
homepage: https://github.com/klisiewicz/fluent-assertions

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  test: ^1.17.4

dev_dependencies:
  lint: ^1.5.3
