name: fluent_assertions
description: A very extensive set of extension methods that allow you to more naturally specify the expected outcome of a TDD or BDD-style unit tests.
version: 0.5.1
homepage: https://github.com/klisiewicz/fluent-assertions

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  test: ^1.25.7

dev_dependencies:
  lint: ^2.3.0
