name: fluent_assertions
description: Fluent Assertions library written in Dart.
version: 0.5.0
homepage: https://github.com/klisiewicz/fluent-assertions

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: ^1.20.4

dev_dependencies:
  lint: ^1.8.1
